= ReadMe test
Author
v0.1
:compat-mode!:
:kroki-server-url: https://kroki.io
:sectnums:
// Table of Contents
:toc:

== Introduction

[plantuml, format="svg"]
----
@startuml

class ClassA #lightgreen {
    +addNote(text: string): void
}

class ClassB #yellow {
    +theEnd()
}

ClassA ..> ClassB: uses
ClassB ..> ClassB: destroy

legend left
  green - new classes
  yellow - modified classes
endlegend

@enduml
----

== Test area finish

The text [.underline]##underline me## is underlined.

The text [.underline]*underline me* is underlined.


[listing]
....
listing
a > b
....

[example]
....
example
a > b
....


[unknown]
....
unknown
a > b
....


[code]
....
code
a > b
....


[quote]
====
quote
a > b
====


This sidebar is short, #so a styled paragraph# will do.


[sidebar]
This sidebar is short, #so a styled paragraph# will do.
This sidebar is short, so a styled paragraph will do.
This sidebar is short, so a styled paragraph will do.
This sidebar is short, so a styled paragraph will do.
This sidebar is short, so a styled paragraph will do.
This sidebar is short, so a styled paragraph will do.
This sidebar is short, so a styled paragraph will do.
This sidebar is short, so a styled paragraph will do.
This sidebar is short, so a styled paragraph will do.


[NOTE]
====
Remember the milk.
====


[NOTE]
Remember the milk.



